version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    build: 
        context: ./spring-boot-app
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:10-alpine

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
  nodejs_service:
    container_name: nodejs
    build: ./node-app
    ports:
      - 8081:8081